import Notes from "./pages/Notes";

const notes = [
    {id: 1, title: 'how to create Online presence', details: 'Lorem ipsum dolor sit amet. Aut aspernatur autem quo debitis officiis id laudantium rerum aut quam dolor. Est accusamus voluptatem vel neque ipsum At eaque pariatur. Sed voluptas doloribus est saepe animi vel nisi error ab natus nihil. A reprehenderit esse qui exercitationem quod aut optio commodi vel neque nisi sit doloremque galisum. Sed officia veniam ex nihil cupiditate et iure ipsum cum galisum consectetur. Ea porro laboriosam aut inventore ullam sit rerum autem est nihil nulla sit reprehenderit iste nam atque quaerat rem vero sequi. Sed culpa facere qui eligendi voluptatem id sapiente sint. Quo voluptas facilis sit ipsam corporis 33 reiciendis iure sed mollitia magnam. Ut voluptatem amet ut quia quis et similique voluptatem est dicta maiores sit saepe assumenda qui quam iste eum deserunt recusandae. Aut suscipit nihil sit aspernatur quia ut dolor quam qui animi illo est ducimus quod. Eos commodi sunt quo molestias doloribus ut earum quaerat sit ipsum alias et perspiciatis fuga aut nobis dolor id libero autem.', date: 'August 7th, 2023'},
    {id: 2, title: 'how to market your brand', details: 'Lorem ipsum dolor sit amet. Aut aspernatur autem quo debitis officiis id laudantium rerum aut quam dolor. Est accusamus voluptatem vel neque ipsum At eaque pariatur. Sed voluptas doloribus est saepe animi vel nisi error ab natus nihil. A reprehenderit esse qui exercitationem quod aut optio commodi vel neque nisi sit doloremque galisum. Sed officia veniam ex nihil cupiditate et iure ipsum cum galisum consectetur. Ea porro laboriosam aut inventore ullam sit rerum autem est nihil nulla sit reprehenderit iste nam atque quaerat rem vero sequi. Sed culpa facere qui eligendi voluptatem id sapiente sint. Quo voluptas facilis sit ipsam corporis 33 reiciendis iure sed mollitia magnam. Ut voluptatem amet ut quia quis et similique voluptatem est dicta maiores sit saepe assumenda qui quam iste eum deserunt recusandae. Aut suscipit nihil sit aspernatur quia ut dolor quam qui animi illo est ducimus quod. Eos commodi sunt quo molestias doloribus ut earum quaerat sit ipsum alias et perspiciatis fuga aut nobis dolor id libero autem.', date: 'August 7th, 2023'},
    {id: 3, title: 'create amazing designs online using Canva', details: 'Lorem ipsum dolor sit amet. Aut aspernatur autem quo debitis officiis id laudantium rerum aut quam dolor. Est accusamus voluptatem vel neque ipsum At eaque pariatur. Sed voluptas doloribus est saepe animi vel nisi error ab natus nihil. A reprehenderit esse qui exercitationem quod aut optio commodi vel neque nisi sit doloremque galisum. Sed officia veniam ex nihil cupiditate et iure ipsum cum galisum consectetur. Ea porro laboriosam aut inventore ullam sit rerum autem est nihil nulla sit reprehenderit iste nam atque quaerat rem vero sequi. Sed culpa facere qui eligendi voluptatem id sapiente sint. Quo voluptas facilis sit ipsam corporis 33 reiciendis iure sed mollitia magnam. Ut voluptatem amet ut quia quis et similique voluptatem est dicta maiores sit saepe assumenda qui quam iste eum deserunt recusandae. Aut suscipit nihil sit aspernatur quia ut dolor quam qui animi illo est ducimus quod. Eos commodi sunt quo molestias doloribus ut earum quaerat sit ipsum alias et perspiciatis fuga aut nobis dolor id libero autem.', date: 'August 7th, 2023'},
    {id: 4, title: 'Benefits of Communal Living', details: 'Lorem ipsum dolor sit amet. Aut aspernatur autem quo debitis officiis id laudantium rerum aut quam dolor. Est accusamus voluptatem vel neque ipsum At eaque pariatur. Sed voluptas doloribus est saepe animi vel nisi error ab natus nihil. A reprehenderit esse qui exercitationem quod aut optio commodi vel neque nisi sit doloremque galisum. Sed officia veniam ex nihil cupiditate et iure ipsum cum galisum consectetur. Ea porro laboriosam aut inventore ullam sit rerum autem est nihil nulla sit reprehenderit iste nam atque quaerat rem vero sequi. Sed culpa facere qui eligendi voluptatem id sapiente sint. Quo voluptas facilis sit ipsam corporis 33 reiciendis iure sed mollitia magnam. Ut voluptatem amet ut quia quis et similique voluptatem est dicta maiores sit saepe assumenda qui quam iste eum deserunt recusandae. Aut suscipit nihil sit aspernatur quia ut dolor quam qui animi illo est ducimus quod. Eos commodi sunt quo molestias doloribus ut earum quaerat sit ipsum alias et perspiciatis fuga aut nobis dolor id libero autem.', date: 'August 7th, 2023'}
]

export default notes;